main:
  name: "balloon_kalman"
  version: "1.0.0"
  base_path: 'cwd'
  data_path: "data/sonde" #Path to RadioSonde log files
  data_type: 'csv'
  loop_delay: 1.0 #seconds to delay mainloop to simulate update period
observer:
  name: "KJ4QLP_QTH"
  lat: 37.1548050
  lon: -80.5674639
  alt: 572
kalman:
  sample_time: 1.0 #sample rate for kalman filter, filter output rate
  u_a: [1,1,1] #control input, acceleration tuple: X, Y, Z
  std_acc: .25 #standard deviation of acceleration
  pos_std_meas: [5,5,.2] #standard deviation of position measurement, X Y Z, units = kilometer
  vel_std_meas: [1,1,.2] #standard deviation of velocity measurement, X Y Z, units = km / sec


